
######
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM0NTQ3OCwianRpIjoiODAzYzlhNDUtYWJkYS00OWFlLWIzNzMtMzlkMTY0NGRjNmVkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3MTM1NTg5NjM1YzgzNzljMjgyMmIzOSIsIm5iZiI6MTczMDM0NTQ3OCwiY3NyZiI6ImNkZjc4MTJjLWMxYjgtNDQ0ZS1iNmRjLTE4MjA5NmI4OTkwNyIsImV4cCI6MTczMDQzMTg3OH0.r5No9Z1uX-uyAax2AmSyAfMmiapsuaMRPNL2nBSidfQ

######
### Set manual location
POST http://127.0.0.1:5000/location/set_manual_location
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "latitude": 34.052235,
    "longitude": -118.243683,
    "street": "123 Main St",
    "city": "Los Angeles",
    "state": "CA",
    "country": "USA",
    "postal_code": "90012"
}


### Current Location
POST http://127.0.0.1:5000/location/set_current_location
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "latitude": 40.712776,
    "longitude": -74.005974
} 

