### Set manual location
POST http://127.0.0.1:5000/location/set_manual_location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyOTQxNTEzNSwianRpIjoiMzAyYTQ4ZTAtY2VjNy00MjJlLWI2MzEtYzE2Y2JlMzc0ZjJlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3MTM1NTg5NjM1YzgzNzljMjgyMmIzOSIsIm5iZiI6MTcyOTQxNTEzNSwiY3NyZiI6IjZmNTc4YzJiLWI1M2YtNDZkNy05NTUyLWM4MGEyMjA1YmFlOCIsImV4cCI6MTcyOTUwMTUzNX0.A0uK9cUU8gNZoSO8LQyv_5Zy6UwIW5FW8sEdp0L0HVA
Content-Type: application/json

{
    "latitude": 34.052235,
    "longitude": -118.243683,
    "street": "123 Main St",
    "city": "Los Angeles",
    "state": "CA",
    "country": "USA",
    "postal_code": "90012"
}


### Current Location
POST http://127.0.0.1:5000/location/set_current_location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyOTQxNTEzNSwianRpIjoiMzAyYTQ4ZTAtY2VjNy00MjJlLWI2MzEtYzE2Y2JlMzc0ZjJlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3MTM1NTg5NjM1YzgzNzljMjgyMmIzOSIsIm5iZiI6MTcyOTQxNTEzNSwiY3NyZiI6IjZmNTc4YzJiLWI1M2YtNDZkNy05NTUyLWM4MGEyMjA1YmFlOCIsImV4cCI6MTcyOTUwMTUzNX0.A0uK9cUU8gNZoSO8LQyv_5Zy6UwIW5FW8sEdp0L0HVA
Content-Type: application/json

{
    "latitude": 40.712776,
    "longitude": -74.005974
} 

