
######
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDQ4ODUwNCwianRpIjoiOTIxOThlMTQtYTRlNC00OTkyLWI5NzEtMWI4NWQ2MDllOGE2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3MTM1NTg5NjM1YzgzNzljMjgyMmIzOSIsIm5iZiI6MTczMDQ4ODUwNCwiY3NyZiI6IjA1MzM5MDczLTExYzctNGM2Ni04YWQxLWYyMWU1MWE1Y2U3YSIsImV4cCI6MTczMDU3NDkwNH0.CtgAokUMYQsW_YGjzhAhBy6lgTF9fkvEF9CYfMwxG2Y

######

### Create Meal Reminders
POST http://127.0.0.1:5000/meal/reminders
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "action": "create"
}

### Snooze Reminder
POST http://127.0.0.1:5000/meal/reminders
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "action": "snooze",
    "reminder_id": "6714d05d5eb64346f55fc0be",
    "snooze_duration": 15
}

### Dismiss Reminder
POST http://127.0.0.1:5000/meal/reminders
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "action": "dismiss",
    "reminder_id": "6714d05d5eb64346f55fc0be"
}

### Get Pending Reminders
GET http://127.0.0.1:5000/meal/get_reminders
Authorization: Bearer {{token}}
Content-Type: application/json

### Get Most Recent Reminder
GET http://127.0.0.1:5000/meal/most_recent_reminder
Authorization: Bearer {{token}}
Content-Type: application/json
