######
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDc4NjU3OSwianRpIjoiMjY5NzUzZTMtOGFlMy00OWMyLWJmMDEtNzY1MTZmY2I4YmU3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3Mjk4NTQyYjMxMjk2NmVkMDIxMTZhZCIsIm5iZiI6MTczMDc4NjU3OSwiY3NyZiI6IjU2MWI2OTdjLTIyYWEtNDMwZS1hNTUyLTM3NGUxNzZkZDRiYiIsImV4cCI6MTczMDg3Mjk3OX0.ZFR8UNtwvdl4ZjatH-0aRMPHGVettKgnI4WSInxe9Io

######

### Fetch Recommendations
GET http://localhost:5000/recommendation/get_recommendations?location=45.5088,-73.55&weather=windy&time=2:30 PM
Authorization: Bearer {{token}}
Content-Type: application/json

### manually setting context
POST http://localhost:5000/recommendation/update_context
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "location": "45.5088,-73.554",
  "weather": "sunny",
  "time": "6:00 PM"
}




# location=45.5088,-73.554&weather=sunny&time=8:00 AM
# location=34.0522,-118.2437&weather=clear&time=1:00 PM
# location=39.7392,-104.9903&weather=rainy&time=6:45 PM
# location=61.2181,-149.9003&weather=snowy&time=10:15 PM
# location=33.4484,-112.0740&weather=windy&time=2:30 PM
# location=47.6062,-122.3321&weather=foggy&time=5:45 AM
# location=25.7617,-80.1918&weather=stormy&time=12:00 PM
