### Get Restaurants
GET http://127.0.0.1:5000/restaurants/list?offset=200&limit=50
Content-Type: application/json

### Get Total restaurants
GET http://127.0.0.1:5000/restaurants/total
Content-Type: application/json
