####
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM0NTQ3OCwianRpIjoiODAzYzlhNDUtYWJkYS00OWFlLWIzNzMtMzlkMTY0NGRjNmVkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3MTM1NTg5NjM1YzgzNzljMjgyMmIzOSIsIm5iZiI6MTczMDM0NTQ3OCwiY3NyZiI6ImNkZjc4MTJjLWMxYjgtNDQ0ZS1iNmRjLTE4MjA5NmI4OTkwNyIsImV4cCI6MTczMDQzMTg3OH0.r5No9Z1uX-uyAax2AmSyAfMmiapsuaMRPNL2nBSidfQ
#####

POST http://127.0.0.1:5000/user/update_profile 
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "cuisines": ["Italian", "Mexican"],
    "indoor_activities": ["Reading", "Gaming"],
    "outdoor_activities": ["Hiking", "Cycling"],
    "restaurants_visited": ["Olive Garden", "Chipotle"],
    "indoor_places_visited": ["Library", "Museum"],
    "outdoor_places_visited": ["Park", "Beach"],
    "preferred_meal_time": [
        {
            "meal": "breakfast",
            "time": "8:00 AM - 10:00 AM"
        },
        {
            "meal": "lunch",
            "time": "12:00 PM"
        },
        {
            "meal": "dinner",
            "time": "8:00 PM"
        }
    ],
    "other_preferences": ["Vegan", "Non-Smoking","Dancing"]
}

### Get User Preferences Request
GET http://127.0.0.1:5000/user/get_preferences
Authorization: Bearer {{token}}
Content-Type: application/json
