### Update Preferences Request### Update Preferences Request
POST http://127.0.0.1:5000/user/update_profile/6711cf78b8e847a1317a4d4f
Content-Type: application/json

{
    "cuisines": ["Italian", "Mexican"],
    "indoor_activities": ["Reading", "Gaming"],
    "outdoor_activities": ["Hiking", "Cycling"],
    "restaurants_visited": ["Olive Garden", "Chipotle"],
    "indoor_places_visited": ["Library", "Museum"],
    "outdoor_places_visited": ["Park", "Beach"],
    "other_preferences": ["Vegan", "Non-Smoking"]
}