### Login Request
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
    "email": "jonathan@example.com",
    "password": "jonathan1234"
}

### Sign-up request
POST http://127.0.0.1:5000/auth/signup
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "janen@example.com",
    "password": "password1234"
}
